# ages
AGE_CHOICES = [
    ('4', '0-4'),
    ('9', '5-9'),
    ( '14', '10-14'),
    ( '19', '15-19'),
    ( '24', '20-24'),
    ( '29', '25-29'),
    ( '34', '30-34'),
    ( '39', '35-39'),
    ( '44', '40-44'),
    ( '49', '45-49'),
    ( '54', '50-54'),
    ( '59', '55-59'),
    ( '64', '60-64'),
    ( '69', '65-69'),
    ( '74', '70-74'),
    ( '79', '75-79'),
    ('80', '80+'),
]

# gender
GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', 'Corporate'),
        ('Z','Gender not applicable'),
        ('O', 'Other'),
    ]


# band codes
BAND_CHOICES = [
    ('BNC01', '1 - 49'),
    ('BNC02', '50 - 100'),
    ('BNC03', '101 - 500'),
    ('BNC04', '501 - 1000'),
    ('BNC05', '1001 - 1500'),
    ('BNC06', '1501 - 2500'),
    ('BNC07', '2501 - 3500'),
    ('BNC08', '3501 - 5000'),
    ('BNC09', '5001 - 7500'),
    ('BNC10', '7501 - 10000'),
    ('BNC11', '10001 - 15000'),
    ('BNC12', '15001 - 20000'),
    ('BNC13', '20001 - 25000'),
    ('BNC14', '25001 - 30000'),
    ('BNC15', '30001 - 35000'),
    ('BNC16', '35001 - 40000'),
    ('BNC17', '40001 - 45000'),
    ('BNC18', '45001 - 50000'),
    ('BNC19', '50001 - 70000'),
    ('BNC20', '70001 - 150000'),
    ('BNC21','150001-250000'),
    ('BNC22', 'Any other band'),
]

# wallet choices
WALLET_CHOICES = [
    ('W01', 'Customers with one wallet'),
    ('W02', 'Customers with 2 wallets'),
    ('W03', 'Customers with 3 wallets'),
    ('W04', 'Customers with 4 wallets'),
    ('W05', 'Customers with 5 wallets'),
    ('W06', 'Customers with 6 wallets'),
    ('W07', 'Customers with 7 wallets'),
    ('W08', 'Customers with 8 wallets'),
    ('W09', 'Customers with 9 wallets'),
    ('W10', 'Customers with 10 wallets'),
    ('W11', 'Customers with more than 10 wallets'),
    ('W99', 'Other customer wallets'),
]

# interoperability choices
INTEROP_CHOICES = [
    ('OIT01', 'P2P transactions'),
    ('OIT02', 'Agent to agent wallet'),
    ('OIT03', 'Till transactions to another network'),
    ('OIT04', 'Paybill transactions to another network'),
    ('OIT05', 'B2P wallet to another network'),
    ('OIT99', 'Other interoperability payment (specify)'),
]


# sub transaction types
SUB_TRANSACTION_CHOICES = [
    ('P2P', 'Person to Person payments'),
    ('B2E', 'Bank to E-wallet'),
    ('E2B', 'E-Wallet to Bank'),
    ('ATMD', 'ATM cash deposits at banks'),
    ('ATMW', 'ATM cash withdrawals from banks'),
    ('ARTP', 'Airtime purchase'),
    ('DTP', 'Data purchases'),
    ('P2B01', 'Person to Business payments'),
    ('P2B02', 'Person to Business payments'),
    ('P2B03', 'Person to Business payments'),
    ('P2B04', 'Person to Business payments'),
    ('P2B05', 'Person to Business payments'),
    ('P2B06', 'Person to Business payments'),
    ('P2B07', 'Person to Business payments'),
    ('P2B08', 'Person to Business payments'),
    ('P2B09', 'Person to Business payments'),
    ('P2B10', 'Person to Business payments'),
    ('P2B11', 'Person to Business payments'),
    ('P2B12', 'Person to Business payments'),
    ('P2B13', 'Person to Business payments'),
    ('P2B14', 'Person to Business payments'),
    ('P2B15', 'Person to Business payments'),
    ('P2B16', 'Person to Business payments'),
    ('P2B17', 'Person to Business payments'),
    ('P2B18', 'Person to Business payments'),
    ('P2B19', 'Person to Business payments'),
    ('P2B20', 'Person to Business payments'),
    ('P2B21', 'Person to Business payments'),
    ('P2B22', 'Person to Business payments'),
    ('P2B23', 'Person to Business payments'),
    ('P2B24', 'Person to Business payments'),
    ('P2G01', 'Person to Government payments'),
    ('P2G02', 'Person to Government payments'),
    ('P2G99', 'Person to Government payments'),
    ('G2P01', 'Government to Person payments'),
    ('G2P02', 'Government to Person payments'),
    ('G2P99', 'Government to Person payments'),
    ('G2B01', 'Government to Business payments'),
    ('G2B02', 'Government to Business payments'),
    ('G2B99', 'Government to Business payments'),
    ('BG2P01', 'Business or Government to Person payments'),
    ('BG2P02', 'Business or Government to Person payments'),
    ('BG2P99', 'Business or Government to Person payments'),
    ('OTCD', 'Other Transaction Code'),
]

TRANSACTION_CHOICES = [
    ('TXNC01', 'Person to Person payments'),
    ('TXNC02', 'Bank to E-wallet'),
    ('TXNC03', 'E-Wallet to Bank'),
    ('TXNC04', 'ATM cash deposits at banks'),
    ('TXNC05', 'ATM cash withdrawals from banks'),
    ('TXNC06', 'Airtime purchase'),
    ('TXNC07', 'Data purchases'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC08', 'Person to Business payments'),
    ('TXNC09', 'Person to Government payments'),
    ('TXNC09', 'Person to Government payments'),
    ('TXNC09', 'Person to Government payments'),
    ('TXNC10', 'Government to Person payments'),
    ('TXNC10', 'Government to Person payments'),
    ('TXNC10', 'Government to Person payments'),
    ('TXNC11', 'Government to Business payments'),
    ('TXNC11', 'Government to Business payments'),
    ('TXNC11', 'Government to Business payments'),
    ('TXNC12', 'Business or Government to Person payments'),
    ('TXNC12', 'Business or Government to Person payments'),
    ('TXNC12', 'Business or Government to Person payments'),
    ('TXNC13', 'Other Transaction Code'),
]

# sub county code
SUB_COUNTY_CHOICES = [
    ('0101', 'CHANGAMWE'),
    ('0102', 'JOMVU'),
    ('0103', 'KISAUNI'),
    ('0104', 'LIKONI'),
    ('0105', 'MVITA'),
    ('0106', 'NYALI'),
    ('0201', 'KINANGO'),
    ('0202', 'LUNGA LUNGA'),
    ('0203', 'MATUGA'),
    ('0204', 'MSAMBWENI'),
    ('0205', 'SAMBURU'),
    ('0301', 'CHONYI'),
    ('0302', 'GANZE'),
    ('0303', 'KALOLENI'),
    ('0304', 'KAUMA'),
    ('0305', 'KILIFI NORTH'),
    ('0306', 'KILIFI SOUTH'),
    ('0307', 'MAGARINI'),
    ('0308', 'MALINDI'),
    ('0309', 'RABAI'),
    ('0401', 'TANA DELTA'),
    ('0402', 'TANA NORTH'),
    ('0403', 'TANA RIVER'),
    ('0501', 'LAMU EAST'),
    ('0502', 'LAMU WEST'),
    ('0601', 'MWATATE'),
    ('0602', 'TAITA'),
    ('0603', 'TAVETA'),
    ('0604', 'VOI'),
    ('0701', 'BALAMBALA'),
    ('0702', 'DADAAB'),
    ('0703', 'FAFI'),
    ('0704', 'GARISSA'),
    ('0705', 'HULUGHO'),
    ('0706', 'IJARA'),
    ('0707', 'LAGDERA'),
    ('0801', 'BUNA'),
    ('0802', 'ELDAS'),
    ('0803', 'HABASWEIN'),
    ('0804', 'TARBAJ'),
    ('0805', 'WAJIR EAST'),
    ('0806', 'WAJIR NORTH'),
    ('0807', 'WAJIR SOUTH'),
    ('0808', 'WAJIR WEST'),
    ('0901', 'MANDERA WEST'),
    ('0902', 'BANISA'),
    ('0903', 'KOTULO'),
    ('0904', 'LAFEY'),
    ('0905', 'MANDERA CENTRAL'),
    ('0906', 'MANDERA EAST'),
    ('0907', 'MANDERA NORTH'),
    ('1001', 'LOIYANGALANI'),
    ('1002', 'MARSABIT CENTRAL'),
    ('1003', 'MARSABIT NORTH'),
    ('1004', 'MARSABIT SOUTH'),
    ('1005', 'MOYALE'),
    ('1006', 'NORTH HORR'),
    ('1007', 'SOLOLO'),
    ('1101', 'GARBATULLA'),
    ('1102', 'ISIOLO'),
    ('1103', 'MERTI'),
    ('1202', 'BUURI WEST'),
    ('1203', 'IGEMBE CENTRAL'),
    ('1204', 'IGEMBE NORTH'),
    ('1205', 'IGEMBE SOUTH'),
    ('1206', 'IMENTI NORTH'),
    ('1207', 'IMENTI SOUTH'),
    ('1208', 'MERU CENTRAL'),
    ('1209', 'TIGANIA CENTRAL'),
    ('1210', 'TIGANIA EAST'),
    ('1211', 'TIGANIA WEST'),
    ('1301', 'IGAMBANG\'OMBE'),
    ('1302', 'MAARA'),
    ('1303', 'MERU SOUTH'),
    ('1304', 'THARAKA NORTH'),
    ('1305', 'THARAKA SOUTH'),
    ('1401', 'EMBU EAST'),
    ('1402', 'EMBU NORTH'),
    ('1403', 'EMBU WEST'),
    ('1404', 'MBEERE SOUTH'),
    ('1405', 'MBEERE NORTH'),
    ('1501', 'IKUTHA'),
    ('1502', 'KATULANI'),
    ('1503', 'KISASI'),
    ('1504', 'KITUI CENTRAL'),
    ('1505', 'KITUI WEST'),
    ('1506', 'KYUSO'),
    ('1507', 'LOWER YATTA'),
    ('1508', 'MATINYANI'),
    ('1509', 'MIGWANI'),
    ('1510', 'MUMONI'),
    ('1511', 'MUTITU'),
    ('1512', 'MUTITU NORTH'),
    ('1513', 'MUTOMO'),
    ('1514', 'MWINGI CENTRAL'),
    ('1515', 'MWINGI EAST'),
    ('1516', 'NZAMBANI'),
    ('1517', 'THAGICU'),
    ('1518', 'TSEIKURU'),
    ('1601', 'ATHI RIVER'),
    ('1602', 'KALAMA'),
    ('1603', 'KANGUNDO'),
    ('1604', 'KATHIANI'),
    ('1605', 'MACHAKOS'),
    ('1606', 'MASINGA'),
    ('1607', 'MATUNGULU'),
    ('1608', 'MWALA'),
    ('1609', 'YATTA'),
    ('1701', 'KATHONZWENI'),
    ('1702', 'KIBWEZI'),
    ('1703', 'KILUNGU'),
    ('1704', 'MAKINDU'),
    ('1705', 'MAKUENI'),
    ('1706', 'MBOONI EAST'),
    ('1707', 'MBOONI WEST'),
    ('1708', 'MUKAA'),
    ('1709', 'NZAUI'),
    ('1801', 'KINANGOP'),
    ('1802', 'NYANDARUA SOUTH'),
    ('1803', 'MIRANGINE'),
    ('1804', 'KIPIPIRI'),
    ('1805', 'NYANDARUA CENTRAL'),
    ('1806', 'NYANDARUA WEST'),
    ('1807', 'NYANDARUA NORTH'),
    ('1901', 'TETU'),
    ('1902', 'KIENI EAST'),
    ('1903', 'KIENI WEST'),
    ('1904', 'MATHIRA EAST'),
    ('1905', 'MATHIRA WEST'),
    ('1906', 'NYERI SOUTH'),
    ('1907', 'MUKURWE-INI'),
    ('1908', 'NYERI CENTRAL'),
    ('2001', 'KIRINYAGA CENTRAL'),
    ('2002', 'KIRINYAGA EAST'),
    ('2003', 'KIRINYAGA WEST'),
    ('2004', 'MWEA EAST'),
    ('2005', 'MWEA WEST'),
    ('2101', 'MURANG\'A EAST'),
    ('2102', 'KANGEMA'),
    ('2103', 'MATHIOYA'),
    ('2104', 'KAHURO'),
    ('2105', 'MURANG\'A SOUTH'),
    ('2106', 'GATANGA'),
    ('2107', 'KIGUMO'),
    ('2108', 'KANDARA'),
    ('2201', 'GATUNDU NORTH'),
    ('2202', 'GATUNDU SOUTH'),
    ('2203', 'GITHUNGURI'),
    ('2204', 'JUJA'),
    ('2205', 'KABETE'),
    ('2206', 'KIAMBAA'),
    ('2207', 'KIAMBU'),
    ('2208', 'KIKUYU'),
    ('2209', 'LARI'),
    ('2210', 'LIMURU'),
    ('2211', 'RUIRU'),
    ('2212', 'THIKA EAST'),
    ('2213', 'THIKA WEST'),
    ('2301', 'KIBISH'),
    ('2302', 'LOIMA'),
    ('2303', 'TURKANA CENTRAL'),
    ('2304', 'TURKANA EAST'),
    ('2305', 'TURKANA NORTH'),
    ('2306', 'TURKANA SOUTH'),
    ('2307', 'TURKANA WEST'),
    ('2401', 'KIPKOMO'),
    ('2402', 'POKOT CENTRAL'),
    ('2403', 'POKOT NORTH'),
    ('2404', 'POKOT SOUTH'),
    ('2405', 'WEST POKOT'),
    ('2501', 'SAMBURU CENTRAL'),
    ('2502', 'SAMBURU EAST'),
    ('2503', 'SAMBURU NORTH'),
    ('2601', 'TRANS NZOIA WEST'),
    ('2602', 'TRANS NZOIA EAST'),
    ('2603', 'KWANZA'),
    ('2604', 'ENDEBESS'),
    ('2605', 'KIMININI'),
    ('2701', 'AINABKOI'),
    ('2702', 'KAPSERET'),
    ('2703', 'KESSES'),
    ('2704', 'MOIBEN'),
    ('2705', 'SOY'),
    ('2706', 'TURBO'),
    ('2801', 'KEIYO NORTH'),
    ('2802', 'KEIYO SOUTH'),
    ('2803', 'MARAKWET EAST'),
    ('2804', 'MARAKWET WEST'),
    ('2901', 'CHESUMEI'),
    ('2902', 'NANDI CENTRAL'),
    ('2903', 'NANDI EAST'),
    ('2904', 'NANDI NORTH'),
    ('2905', 'NANDI SOUTH'),
    ('2906', 'TINDERET'),
    ('3001', 'BARINGO CENTRAL'),
    ('3002', 'BARINGO NORTH'),
    ('3003', 'EAST POKOT'),
    ('3004', 'KOIBATEK'),
    ('3005', 'MARIGAT'),
    ('3006', 'MOGOTIO'),
    ('3007', 'TIATY EAST'),
    ('3008', 'LAKE BARINGO'),
    ('3101', 'LAIKIPIA CENTRAL'),
    ('3102', 'LAIKIPIA EAST'),
    ('3103', 'LAIKIPIA NORTH'),
    ('3104', 'LAIKIPIA WEST'),
    ('3105', 'NYAHURURU'),
    ('3201', 'GILGIL'),
    ('3202', 'KURESOI NORTH'),
    ('3203', 'KURESOI SOUTH'),
    ('3204', 'MOLO'),
    ('3205', 'NAIVASHA'),
    ('3206', 'NAKURU EAST'),
    ('3207', 'NAKURU NORTH'),
    ('3208', 'NAKURU WEST'),
    ('3209', 'NJORO'),
    ('3210', 'RONGAI'),
    ('3211', 'SUBUKIA'),
    ('3301', 'NAROK EAST'),
    ('3302', 'NAROK NORTH'),
    ('3303', 'NAROK SOUTH'),
    ('3304', 'NAROK WEST'),
    ('3305', 'TRANS MARA EAST'),
    ('3306', 'TRANS MARA WEST'),
    ('3401', 'ISINYA'),
    ('3402', 'KAJIADO CENTRAL'),
    ('3403', 'KAJIADO NORTH'),
    ('3404', 'KAJIADO WEST'),
    ('3405', 'LOITOKITOK'),
    ('3406', 'MASHUURU'),
    ('3501', 'BELGUT'),
    ('3502', 'BURETI'),
    ('3503', 'KERICHO EAST'),
    ('3504', 'KIPKELION'),
    ('3505', 'LONDIANI'),
    ('3506', 'SOIN SIGOWET'),
    ('3601', 'BOMET EAST'),
    ('3602', 'CHEPALUNGU'),
    ('3603', 'KONOIN'),
    ('3604', 'SOTIK'),
    ('3605', 'BOMET CENTRAL'),
    ('3701', 'BUTERE'),
    ('3702', 'KAKAMEGA CENTRAL'),
    ('3703', 'KAKAMEGA EAST'),
    ('3704', 'KAKAMEGA NORTH'),
    ('3705', 'KAKAMEGA SOUTH'),
    ('3706', 'KHWISERO'),
    ('3707', 'LIKUYANI'),
    ('3708', 'LUGARI'),
    ('3709', 'MATETE'),
    ('3710', 'MATUNGU'),
    ('3711', 'MUMIAS EAST'),
    ('3712', 'MUMIAS WEST'),
    ('3713', 'NAVAKHOLO'),
    ('3801', 'EMUHAYA'),
    ('3802', 'VIHIGA'),
    ('3803', 'SABATIA'),
    ('3804', 'LUANDA'),
    ('3805', 'HAMISI'),
    ('3901', 'BUMULA'),
    ('3902', 'BUNGOMA CENTRAL'),
    ('3903', 'BUNGOMA EAST'),
    ('3904', 'BUNGOMA NORTH'),
    ('3905', 'BUNGOMA SOUTH'),
    ('3906', 'CHEPTAIS'),
    ('3907', 'KIMILILI'),
    ('3909', 'BUNGOMA WEST'),
    ('3910', 'TONGAREN'),
    ('3911', 'WEBUYE WEST'),
    ('3912', 'MT ELGON FOREST'),
    ('4001', 'BUNYALA'),
    ('4002', 'BUSIA'),
    ('4003', 'BUTULA'),
    ('4004', 'NAMBALE'),
    ('4005', 'SAMIA'),
    ('4006', 'TESO NORTH'),
    ('4007', 'TESO SOUTH'),
    ('4101', 'SIAYA'),
    ('4102', 'GEM'),
    ('4103', 'UGENYA'),
    ('4104', 'UGUNJA'),
    ('4105', 'BONDO'),
    ('4106', 'RARIEDA'),
    ('4201', 'KISUMU EAST'),
    ('4202', 'KISUMU CENTRAL'),
    ('4203', 'KISUMU WEST'),
    ('4204', 'SEME'),
    ('4205', 'MUHORONI'),
    ('4206', 'NYANDO'),
    ('4207', 'NYAKACH'),
    ('4301', 'HOMA BAY'),
    ('4302', 'NDHIWA'),
    ('4303', 'RACHUONYO NORTH'),
    ('4304', 'RACHUONYO EAST'),
    ('4305', 'RACHUONYO SOUTH'),
    ('4306', 'RANGWE'),
    ('4307', 'SUBA NORTH'),
    ('4308', 'SUBA SOUTH'),
    ('4401', 'AWENDO'),
    ('4402', 'KURIA EAST'),
    ('4403', 'KURIA WEST'),
    ('4404', 'NYATIKE'),
    ('4405', 'RONGO'),
    ('4406', 'SUNA EAST'),
    ('4407', 'SUNA WEST'),
    ('4408', 'URIRI'),
    ('4501', 'ETAGO'),
    ('4502', 'GUCHA'),
    ('4503', 'GUCHA SOUTH'),
    ('4504', 'KENYENYA'),
    ('4505', 'KISII CENTRAL'),
    ('4506', 'KISII SOUTH'),
    ('4507', 'KITUTU CENTRAL'),
    ('4508', 'MARANI'),
    ('4509', 'MASABA SOUTH'),
    ('4510', 'NYAMACHE'),
    ('4511', 'SAMETA'),
    ('4601', 'BORABU'),
    ('4602', 'MANGA'),
    ('4603', 'MASABA NORTH'),
    ('4604', 'NYAMIRA NORTH'),
    ('4605', 'NYAMIRA SOUTH'),
    ('4701', 'DAGORETTI'),
    ('4702', 'EMBAKASI'),
    ('4703', 'KAMUKUNJI'),
    ('4704', 'KASARANI'),
    ('4705', 'KIBRA'),
    ('4706', 'LANG\'ATA'),
    ('4707', 'MAKADARA'),
    ('4708', 'MATHARE'),
    ('4709', 'NJIRU'),
    ('4710', 'STAREHE'),
    ('4711', 'WESTLANDS'),
]

# counties
counties = [
    ('001', 'MOMBASA'),
    ('002', 'KWALE'),
    ('003', 'KILIFI'),
    ('004', 'TANA RIVER'),
    ('005', 'LAMU'),
    ('006', 'TAITA/TAVETA'),
    ('007', 'GARISSA'),
    ('008', 'WAJIR'),
    ('009', 'MANDERA'),
    ('010', 'MARSABIT'),
    ('011', 'ISIOLO'),
    ('012', 'MERU'),
    ('013', 'THARAKA-NITHI'),
    ('014', 'EMBU'),
    ('015', 'KITUI'),
    ('016', 'MACHAKOS'),
    ('017', 'MAKUENI'),
    ('018', 'NYANDARUA'),
    ('019', 'NYERI'),
    ('020', 'KIRINYAGA'),
    ('021', 'MURANG\'A'),
    ('022', 'KIAMBU'),
    ('023', 'TURKANA'),
    ('024', 'WEST POKOT'),
    ('025', 'SAMBURU'),
    ('026', 'TRANS NZOIA'),
    ('027', 'UASIN GISHU'),
    ('028', 'ELGEYO/MARAKWET'),
    ('029', 'NANDI'),
    ('030', 'BARINGO'),
    ('031', 'LAIKIPIA'),
    ('032', 'NAKURU'),
    ('033', 'NAROK'),
    ('034', 'KAJIADO'),
    ('035', 'KERICHO'),
    ('036', 'BOMET'),
    ('037', 'KAKAMEGA'),
    ('038', 'VIHIGA'),
    ('039', 'BUNGOMA'),
    ('040', 'BUSIA'),
    ('041', 'SIAYA'),
    ('042', 'KISUMU'),
    ('043', 'HOMA BAY'),
    ('044', 'MIGORI'),
    ('045', 'KISII'),
    ('046', 'NYAMIRA'),
    ('047', 'NAIROBI CITY'),
]

PSP_ID_OTHER_CHOICES = [
    ('0800001', 'Safaricom Plc'),
    ('0800002', 'Airtel Money Kenya Limited'),
    ('0800003', 'Telkom Kenya Limited'),
    ('0800004', 'Mobile Pay Limited'),
    ('0800005', 'Kenswitch Limited'),
    ('0800006', 'Interswitch East Africa (K) Limited'),
    ('0800007', 'Integrated Payment Services Limited'),
    ('0800008', 'Viewtech Limited'),
    ('0800009', 'Web Tribe Limited'),
    ('0800010', 'Finserve Africa Limited'),
    ('0800011', 'Cellulant Kenya Limited'),
    ('0800012', 'Pesapal Limited'),
    ('0800013', 'Fivespot Limited'),
    ('0800014','Craft Silicon Limited'),
    ('0800015','Virtual Pay International Limited'),
    ('0800016','Direct Pay Limited'),
    ('0800017','Pesawise Services Limited'),
    ('0800018','Paystack Payments Kenya Limited'),
    ('0800019','Wakandi Kenya Limited'),
    ('0800020','Kenya Airports Parking Services (KAPS) Limited'),
    ('0800021','Loop Payco Limited'),
    ('0800022','DLocal Payments Kenya Limited'),
    ('0800023','Pesaflow Limited'),
    ('0800024','Kenya Commerce Exchange Service Bureau Limited'),
    ('0800025','PayU Kenya Limited'),
    ('0800026','Dolcepay Kenya Limited'),
    ('0800027','Unlimint Kenya Limited'),
    ('0800028','Gladys Technologies Limited'),
    ('0800029','Mamlaka Hub and Spoke Limited'),
    ('0800030','Eclectics International Limited'),
    ('0800031','Jumia Payment Services Kenya Limited'),
    ('0800032','Amsuka Capital Limited'),
    ('0800033','Sky World Limited'),
    ('0800034','Kashia Services Limited'),
    ('0800035','Data Integrated Limited'),
    ('0800036','Tanda Agent Limited'),
]

FAILED_TRANSACTION_CODE_CHOICES = [
    ('FTC01', 'Person to person transactions'),
    ('FTC02', 'Wallet to till number transactions'),
    ('FTC03', 'Wallet to paybill number transactions'),
    ('FTC04', 'Same network wallet-to-unregistered mobile money wallet'),
    ('FTC05', 'Cross network wallet-to-mobile number transactions'),
    ('FTC06', 'Cross network wallet-to-paybill number transactions'),
    ('FTC07', 'Cross network wallet-to-till number transactions'),
    ('FTC08', 'Wallet-to-bank transactions'),
    ('FTC09', 'Wallet-to-international wallet transactions'),
    ('FTC10', 'International money transfer-to-wallet transactions'),
    ('FTC11', 'Bulk payments transactions'),
    ('FTC99', 'Other failed transaction code'),
]

MERCHANT_TYPE_CHOICES = [
    ('MERCHTYP01', 'PAYBILL'),
    ('MERCHTYP02', 'TILL'),
    ('MERCHTYP99', 'OTHERS'),
]

MERCHANT_CLASSIFICATION_CODE_CHOICES = [
    ('MCC01', 'Betting activities'),
    ('MCC02', 'Gaming activities'),
    ('MCC03', 'Wholesale'),
    ('MCC04', 'Retail'),
    ('MCC05', 'Oil & Gas'),
    ('MCC06', 'Hospitality & Services'),
    ('MCC07', 'Agriculture'),
    ('MCC08', 'Health'),
    ('MCC09', 'Construction & Engineering'),
    ('MCC10', 'Energy'),
    ('MCC11', 'Professional Services'),
    ('MCC12', 'Transport & logistics'),
    ('MCC13', 'Automotive'),
    ('MCC14', 'Manufacturing'),
    ('MCC15', 'Media & ICT'),
    ('MCC16', 'Education'),
    ('MCC17', 'Religious Institutions'),
    ('MCC18', 'Banking'),
    ('MCC19', 'Saving Cooperative'),
    ('MCC20', 'Insurance'),
    ('MCC21', 'Micro Finance'),
    ('MCC22', 'Tracking Service'),
    ('MCC23', 'Security & Logistics'),
    ('MCC24', 'Embassy'),
    ('MCC25', 'Aviation'),
    ('MCC26', 'National Government'),
    ('MCC27', 'County Government'),
    ('MCC28', 'NGO'),
    ('MCC99', 'Any other (Specify)'),
]

MERCHANT_STATUS_CHOICES = [
    ('ACT30', 'Active 30 Days'),
    ('ACT60', 'Active 60 Days'),
    ('ACT90', 'Active 90 Days'),
    ('INACT', 'Inactive'),
    ('DRMNT', 'Dormant'),
    ('REG', 'Registered'),
    ('UNREG', 'Unregistered'),
]

AGENT_TYPE_CHOICES = [
    ('SUPAG', 'Super Agent'),
    ('AG', 'Agent'),
]

AGENT_STATUS_CHOICES = [
    ('ACT30', 'Active 30 Days'),
    ('DRMNT', 'Dormant'),
    ('SUS','Suspended'),
    ('TER','Terminated'),
    ('ACT60', 'Active 60 Days'),
    ('ACT90', 'Active 90 Days'),
    ('INACT', 'Inactive'),
    ('REG', 'Registered'),
    ('UNREG', 'Unregistered'),
]

PRODUCT_CATEGORY_CHOICES = [
    ('PCC01', 'PSP own products (owned and operated by PSP end to end)'),
    ('PCC02', 'PSP partnership products with other entities'),
]

PRODUCT_OWNERSHIP_CATEGORY_CHOICES = [
    ('TPOCC01', 'Mobile PSP'),
    ('TPOCC02', 'Bank'),
    ('TPOCC03', 'Switches'),
    ('TPOCC04', 'Gateways'),
    ('TPOCC05', 'Business merchants'),
    ('TPOCC06', 'Utility merchants'),
    ('TPOCC99', 'Specify'),
]

PRODUCT_TRANSACTION_CODE_CHOICES = [
    ('PTT01', 'Deposit'),
    ('PTT02', 'Withdrawal'),
    ('PTT04', 'Disbursement'),
    ('PTT05', 'Transfers'),
    ('PTT06', 'Repayments'),
    ('PTT07', 'Balances'),
    ('PTT08', 'Defaults'),
    ('PTT09','payments'),
    ('PTT99', 'Any other'),
]

STATUS_CODE_CHOICES = [
    ('ACT30', 'Active 30 Days'),
    ('ACT60', 'Active 60 Days'),
    ('ACT90', 'Active 90 Days'),
    ('INACT', 'Inactive'),
    ('DRMNT', 'Dormant'),
    ('REG', 'Registered'),
    ('UNREG', 'Unregistered'),
]

DEBIT_TYPE_CODE_CHOICES = [
    ('DBT01', 'Banks charges'),
    ('DBT02', 'Management fees'),
    ('DBT03', 'Stamp duty'),
    ('DBT04', 'Donations'),
    ('DBT05', 'Custody fees'),
    ('DBT06', 'Audit fees'),
    ('DBT07', 'Withholding taxes'),
    ('DBT08', 'Field not applicable'),
    ('DBT99', 'Any others debit type'),
]

SECTOR_CODE_CHOICES = [
    ('P2B01','Agriculture,forestry and fishing'),
    ('P2B02', 'Mining and Quarrying'),
    ('P2B03', 'Manufacturing'),
    ('P2B07', 'Electricity, gas, steam and air conditioning supply'),
    ('P2B08', 'Water supply: sewerage, waste management and remediation activities'),
    ('P2B09', 'Construction'),
    ('P2B10', 'Wholesale and retail trade; repair of motor vehicles and motorcycles'),
    ('P2B11', 'Transportation and storage'),
    ('P2B12', 'Accommodation and food service activities'),
    ('P2B13', 'Information and communication'),
    ('P2B14', 'Financial and insurance activities'),
    ('P2B15', 'Real estate activities'),
    ('P2B16', 'Professional, scientific and technical activities'),
    ('P2B17', 'Administrative and support service activities'),
    ('P2B18', 'Public administration and defence; compulsory social security'),
    ('P2B19', 'Education'),
    ('P2B20', 'Human health and social work activities'),
    ('P2B21', 'Arts, entertainment and recreation'),
    ('P2B22', 'Other service activities'),
    ('P2B23', 'Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use'),
    ('P2B24', 'Activities of extraterritorial organizations and bodies'),
    ('P2B99', 'Other sector'),
]

# Education choices
EDUCATION_CHOICES = [
    ('ELAC01', 'Primary'),
    ('ELAC02', 'Secondary'),
    ('ELAC03', 'Bachelor'),
    ('ELAC04', 'Master'),
    ('ELAC05', 'phD'),
    ('ELAC06','Professional education'),
    ('ELAC07','Professional Body'),
    ('ELAC99','Other Details (please specify)')
]

# victims_category choices
VICTIM_CATEGORY_CHOICES = [
    ('VCCD01','Individual'),
    ('VCCD02','Agent'),
    ('VCCD03','Bank'),
    ('VCCD04','Mobile PSP'),
    ('VCCD05','None,no fraud occured'),
    ('VCCD99','Any Other'),
]
# victim Information choices
VICTIM_INFORMATION_CHOICES = [
    ('VICT01','Name'),
    ('VICT02','Age'),
    ('VICT03','Contact number'),
    ('VICT04','Physical location'),
    ('VICT05','Education level'),
]

COMPLAINTS_FREQUENCY_CODE_CHOICES = [ 
    ('CFQC01','First - timer'),
    ('CFQC02','Second - timer'),
    ('CFQC03','Third - timer'),
    ('CFQC04','Fourth - timer'),
    ('CFQC05','Fifth - timer'),
    ('CFQC99','Any other '),
]
REMEDIAL_STATUS_CHOICES = [
    ('REMCST01','Open'),
    ('REMCST02','Closed'),
    ('REMCST03','Not applicable'),
    ('REMCST99',' Other status Code'),
]

COMPLAINTS_CODE_CHOICES=[
    ('CCS01','Unexpected charges'),
    ('CCS02','Undisclosed charges'),
    ('CCS03','Non-receipt of funds sent'),
    ('CCS04','Sending failure'),
    ('CCS05','Product/service not working or unavailable'),
    ('CCS06','Product issued to customer not the right one s/he needed'),
    ('CCS07','Product terms and conditions not displayed or given to customer'),
    ('CCS08','Product terms and conditions not explained clearly and in a simple manner'),
    ('CCS09','Termination of service without prior and sufficient notice'),
    ('CCS10','Paid for service but it has not been provided or activated'),
    ('CCS11','Unauthorised and excessive sending of promotional text messages'),
    ('CCS12','Lack of clear channel for making a compliant'),
    ('CCS13','Resolution of complaint took/takes excessively long'),
    ('CCS14','Lack of a clear recourse mechanism'),
    ('CCS15','Customers data and information disclosed to other parties without prior consent'),
    ('CCS16','No complaints reported'),
    ('CCS99','Other complaint code'),
]

SYSTEM_CATEGORY_OWNER_FLAG_CHOICES = [
    ('Y','PSP owned '),
    ('N','Third party owned'),
    ('YN','No system affected'),
]
THIRD_PARTY_OWNED_CATEGORY_CHOICES = [
    ('TPOCC01',' Mobile PSP '),
    ('TPOCC02',' Bank'),
    ('TPOCC03',' Switches'),
    ('TPOCC04',' Gateways'),
    ('TPOCC05',' Business Merchants'),
    ('TPOCC06','Utility merchants'),
    ('TPOCC99',' Specify'),
    ]
PRODUCT_TYPE_CHOICES = [
    ('PRODT01','Product 1 Credit/mobile loans'),
    ('PRODT02','Product 2 Airtime on Credit '),
    ('PRODT99','Others specify'),
]
SYSTEM_UNAVAILABILITY_CHOICES = [
    ('SSTC01','Total downtime'),
    ('SSTC02','Intermittent downtime'),
    ('SSTC99','Other system availability type')
]

RECOVERY_TIME_CHOICES = [  
    ('RCD01','0 - 5 Minutes'),
    ('RCD02','6 - 10 Minutes'),
    ('RCD03','11 - 20 Minutes'),
    ('RCD04','21 - 30 Minutes'),
    ('RCD05','31 - 45 Minutes'),
    ('RCD06','46 - 60 Minutes'),
    ('RCD07','61 - 90 Minutes'),
    ('RCD08','1 - 2 Hours'),
    ('RCD09','No system available'),
    ('RCD99','Others (Specify)'),
]

DISRUPTION_CODE_CHOICES = [
    ('DT01','Low'),
    ('DT02','Medium'),
    ('DT03','High'),
    ('DT04','None'),
]

INTERRUPTION_CODE_CHOICES = [
    ('ICD01','Network outage'),
    ('ICD02','Vandalism'),
    ('ICD03','Power outage'),
    ('ICD04','Cyber attack'),
    ('ICD05','No interruption experienced'),
    ('ICD99','Others (Specify)'),
]

COUNTRY_CODE_CHOICES = [
    ('AF','Afghanistan'),
    ('AX','Aland Islands'),
    ('AL','Albania'),
    ('DZ','Algeria'),
    ('AS','American Samoa'),
    ('AD','Andorra'),
    ('AO','Angola'),
    ('AI','Anguilla'),
    ('AQ','Antarctica'),
    ('AG','Antigua and Barbuda'),
    ('AR','Argentina'),
    ('AM','Armenia'),
    ('AW','Aruba'),
    ('AU','Australia'),
    ('AT','Austria'),
    ('AZ','Azerbaijan'),
    ('BS','Bahamas'),
    ('BH','Bahrain'),
    ('BD','Bangladesh'),
    ('BB','Barbados'),
    ('BY','Belarus'),
    ('BE','Belgium'),
    ('BZ','Belize'),
    ('BJ','Benin'),
    ('BM','Bermuda'),
    ('BT','Bhutan'),
    ('BO','Bolivia'),
    ('BQ','Bonaire, Sint Eustatius and Saba'),
    ('BA','Bosnia and Herzegovina'),
    ('BW','Botswana'),
    ('BV','Bouvet Island'),
    ('BR','Brazil'),
    ('IO','British Indian Ocean Territory'),
    ('BN','Brunei Darussalam'),
    ('BG','Bulgaria'),
    ('BF','Burkina Faso'),
    ('BI','Burundi'),
    ('KH','Cambodia'),
    ('CM','Cameroon'),
    ('CA','Canada'),
    ('CV','Cape Verde'),
    ('KY','Cayman Islands'),
    ('CF','Central African Republic'),
    ('TD','Chad'),
    ('CL','Chile'),
    ('CN','China'),
    ('CX','Christmas Island'),
    ('CC','Cocos (Keeling) Islands'),
    ('CO','Colombia'),
    ('KM','Comoros'),
    ('CG','Congo'),
    ('CD','Congo, Democratic Republic of the'),
    ('CK','Cook Islands'),
    ('CR','Costa Rica'),
    ('CI','Cote d\'Ivoire'),
    ('HR','Croatia'),
    ('CU','Cuba'),
    ('CW','Curacao'),
    ('CY','Cyprus'),
    ('CZ','Czech Republic'),
    ('DK','Denmark'),
    ('DJ','Djibouti'),
    ('DM','Dominica'),
    ('DO','Dominican Republic'),
    ('EC','Ecuador'),
    ('EG','Egypt'),
    ('SV','El Salvador'),
    ('GQ','Equatorial Guinea'),
    ('ER','Eritrea'),
    ('EE','Estonia'),
    ('ET','Ethiopia'),
    ('FK','Falkland Islands (Malvinas)'),
    ('FO','Faroe Islands'),
    ('FJ','Fiji'),
    ('FI','Finland'),
    ('FR','France'),
    ('GF','French Guiana'),
    ('PF','French Polynesia'),
    ('TF','French Southern Territories'),
    ('GA','Gabon'),
    ('GM','Gambia'),
    ('GE','Georgia'),
    ('DE','Germany'),
    ('GH','Ghana'),
    ('GI','Gibraltar'),
    ('GR','Greece'),
    ('GL','Greenland'),
    ('GD','Grenada'),
    ('GP','Guadeloupe'),
    ('GU','Guam'),
    ('GT','Guatemala'),
    ('GG','Guernsey'),
    ('GN','Guinea'),
    ('GW','Guinea-Bissau'),
    ('GY','Guyana'),
    ('HT','Haiti'),
    ('HM','Heard Island and McDonald Islands'),
    ('VA','Holy See (Vatican City State)'),
    ('HN','Honduras'),
    ('HK','Hong Kong'),
    ('HU','Hungary'),
    ('IS','Iceland'),
    ('IN','India'),
    ('ID','Indonesia'),
    ('IR','Iran, Islamic Republic of'),
    ('IQ','Iraq'),
    ('IE','Ireland'),
    ('IM','Isle of Man'),
    ('IL','Israel'),
    ('IT','Italy'),
    ('JM','Jamaica'),
    ('JP','Japan'),
    ('JE','Jersey'),
    ('JO','Jordan'),
    ('KZ','Kazakhstan'),
    ('KE','Kenya'),
    ('KI','Kiribati'),
    ('KP','Korea, Democratic People\'s Republic of'),
    ('KR','Korea, Republic of'),
    ('KW','Kuwait'),
    ('KG','Kyrgyzstan'),
    ('LA','Lao People\'s Democratic Republic'),
    ('LV','Latvia'),
    ('LB','Lebanon'),
    ('LS','Lesotho'),
    ('LR','Liberia'),
    ('LY','Libyan Arab Jamahiriya'),
    ('LI','Liechtenstein'),
    ('LT','Lithuania'),
    ('LU','Luxembourg'),
    ('MO','Macao'),
    ('MK','Macedonia, the Former Yugoslav Republic of'),
    ('MG','Madagascar'),
    ('MW','Malawi'),
    ('MY','Malaysia'),
    ('MV','Maldives'),
    ('ML','Mali'),
    ('MT','Malta'),
    ('MH','Marshall Islands'),
    ('MQ','Martinique'),
    ('MR','Mauritania'),
    ('MU','Mauritius'),
    ('YT','Mayotte'),
    ('MX','Mexico'),
    ('FM','Micronesia, Federated States of'),
    ('MD','Moldova, Republic of'),
    ('MC','Monaco'),
    ('MN','Mongolia'),
    ('ME','Montenegro'),
    ('MS','Montserrat'),
    ('MA','Morocco'),
    ('MZ','Mozambique'),
    ('MM','Myanmar'),
    ('NA','Namibia'),
    ('NR','Nauru'),
    ('NP','Nepal'),
    ('NL','Netherlands'),
    ('AN','Netherlands Antilles'),
    ('NC','New Caledonia'),
    ('NZ','New Zealand'),
    ('NI','Nicaragua'),
    ('NE','Niger'),
    ('NG','Nigeria'),
    ('NU','Niue'),
    ('NF','Norfolk Island'),
    ('MP','Northern Mariana Islands'),
    ('NO','Norway'),
    ('OM','Oman'),
    ('PK','Pakistan'),
    ('PW','Palau'),
    ('PS','Palestinian Territory, Occupied'),
    ('PA','Panama'),
    ('PG','Papua New Guinea'),
    ('PY','Paraguay'),
    ('PE','Peru'),
    ('PH','Philippines'),
    ('PN','Pitcairn'),
    ('PL','Poland'),
    ('PT','Portugal'),
    ('PR','Puerto Rico'),
    ('QA','Qatar'),
    ('RE','Reunion'),
    ('RO','Romania'),
    ('RU','Russian Federation'),
    ('RW','Rwanda'),
    ('BL','Saint Barthelemy'),
    ('SH','Saint Helena'),
    ('KN','Saint Kitts and Nevis'),
    ('LC','Saint Lucia'),
    ('MF','Saint Martin'),
    ('PM','Saint Pierre and Miquelon'),
    ('VC','Saint Vincent and the Grenadines'),
    ('WS','Samoa'),
    ('SM','San Marino'),
    ('ST','Sao Tome and Principe'),
    ('SA','Saudi Arabia'),
    ('SN','Senegal'),
    ('RS','Serbia'),
    ('SC','Seychelles'),
    ('SL','Sierra Leone'),
    ('SG','Singapore'),
    ('SK','Slovakia'),
    ('SI','Slovenia'),
    ('SB','Solomon Islands'),
    ('SO','Somalia'),
    ('ZA','South Africa'),
    ('GS','South Georgia and the South Sandwich Islands'),
    ('ES','Spain'),
    ('LK','Sri Lanka'),
    ('SD','Sudan'),
    ('SR','Suriname'),
    ('SJ','Svalbard and Jan Mayen'),
    ('SZ','Swaziland'),
    ('SE','Sweden'),
    ('CH','Switzerland'),
    ('SY','Syrian Arab Republic'),
    ('TW','Taiwan, Province of China'),
    ('TJ','Tajikistan'),
    ('TZ','Tanzania, United Republic of'),
    ('TH','Thailand'),
    ('TL','Timor-Leste'),
    ('TG','Togo'),
    ('TK','Tokelau'),
    ('TO','Tonga'),
    ('TT','Trinidad and Tobago'),
    ('TN','Tunisia'),
    ('TR','Turkey'),
    ('TM','Turkmenistan'),
    ('TC','Turks and Caicos Islands'),
    ('TV','Tuvalu'),
    ('UG','Uganda'),
    ('UA','Ukraine'),
    ('AE','United Arab Emirates'),
    ('GB','United Kingdom'),
    ('US','United States'),
    ('UM','United States Minor Outlying Islands'),
    ('UY','Uruguay'),
    ('UZ','Uzbekistan'),
    ('VU','Vanuatu'),
    ('VE','Venezuela'),
    ('VN','Viet Nam'),
    ('VG','Virgin Islands, British'),
    ('VI','Virgin Islands, U.S.'),
    ('WF','Wallis and Futuna'),
    ('EH','Western Sahara'),
    ('YE','Yemen'),
    ('ZM','Zambia'),
    ('ZW','Zimbabwe'),
]

INCIDENT_MODE_CHOICES = [
    ('ICDT01','Malware'),
    ('ICDT02','Exploits'),
    ('ICDT03','Phishing'),
    ('ICDT04','No incident occured'),
    ('ICDT99','Specify')
]
LOSS_TYPE_CHOICES = [
    ('FIN','Financial'),
    ('DAT','Data'),
    ('NLSS','No Loss,no incident occured'),
]
CARD_FLAG_CHOICES = [
    ('P','Physical'),
    ('V','Virtual'),
]
CARD_TYPE_CHOICES=[
    ('CTC01','Credit Card'),
    ('CTC02','Prepaid Card'),
    ('CTC03','Debit Card'),
    ('CTC04','Charge Cards'),
    ('CTC99','Other Card Type'),
]

TIME_CHOICES = [
    ('HH01', '00:00 - 00:59'),
    ('HH02', '01:00 - 01:59'),
    ('HH03', '02:00 - 02:59'),
    ('HH04', '03:00 - 03:59'),
    ('HH05', '04:00 - 04:59'),
    ('HH06', '05:00 - 05:59'),
    ('HH07', '06:00 - 06:59'),
    ('HH08', '07:00 - 07:59'),
    ('HH09', '08:00 - 08:59'),
    ('HH10', '09:00 - 09:59'),
    ('HH11', '10:00 - 10:59'),
    ('HH12', '11:00 - 11:59'),
    ('HH13', '12:00 - 12:59'),
    ('HH14', '13:00 - 13:59'),
    ('HH15', '14:00 - 14:59'),
    ('HH16', '15:00 - 15:59'),
    ('HH17', '16:00 - 16:59'),
    ('HH18', '17:00 - 17:59'),
    ('HH19', '18:00 - 18:59'),
    ('HH20', '19:00 - 19:59'),
    ('HH21', '20:00 - 20:59'),
    ('HH22', '21:00 - 21:59'),
    ('HH23', '22:00 - 22:59'),
    ('HH24', '23:00 - 23:59')
]
CARD_BRAND_TYPE_CHOICES = [
    ('CDB01', 'Visa'),
    ('CDB02', 'MasterCard'),
    ('CDB03', 'American Express'),
    ('CDB04', 'China UnionPay'),
    ('CDB05', 'Japan Credit Bureau (JCB)'),
    ('CDB06', 'GTP'),
    ('CDB07', 'Quick Cash'),
    ('CDB08', 'EuroPay'),
    ('CDB09', 'Diners'),
    ('CDB99', 'Any Other')
]
TRANSACTION_CATEGORY_CHOICES = [
    ('TCC01', 'Local Transactions'),
    ('TCC02', 'International Transactions'),
]
CHANNEL_TYPE_CHOICES = [
    ('CDCH01', 'ATM'),
    ('CDCH02', 'POS'),
    ('CDCH03', 'MPOS'),
    ('CDCH04', 'Quick Reader (QR) Code'),
    ('CDCH05', 'Mobile'),
    ('CDCH06', 'Agent'),
    ('CDCH07', 'Online/E-commerce'),
    ('CDCH08', 'Over The Counter (OTC)'),
    ('CDCH09', 'Wire Transfer (via SWIFT)'),
    ('CDCH10', 'Internet Banking'),
    ('CDCH99', 'Others'),
]
CLASS_CARD_TYPE_CHOICES = [
    ('CDC01', 'Platinum'),
    ('CDC02', 'Gold'),
    ('CDC03', 'Classic'),
    ('CDC99', 'Other'),
]

SUBMISSION_FREQUENCY_CHOICES = [
    ('once_daily', '12:37'),
    ('once_daily', '12:38'),
    ('once_monthly', '00:00 on the 1st day of the month'),
    ('annually', '00:00 on January 1st'),
]

COMPUTATIONAL_TIME_CHOICES = [
    ('HH00', '00:00'),
    ('HH01', '01:00'),
    ('HH02', '02:00'),
    ('HH03', '03:00'),
    ('HH04', '04:00'),
    ('HH05', '05:00'),
    ('HH06', '06:00'),
    ('HH07', '07:00'),
    ('HH08', '08:00'),
    ('HH09', '09:00'),
    ('HH10', '10:00'),
    ('HH11', '11:00'),
    ('HH12', '12:00'),
    ('HH13', '13:00'),
    ('HH14', '14:00'),
    ('HH15', '15:00'),
    ('HH16', '16:00'),
    ('HH17', '17:00'),
    ('HH18', '18:00'),
    ('HH19', '19:00'),
    ('HH20', '20:00'),
    ('HH21', '21:00'),
    ('HH22', '22:00'),
    ('HH23', '23:00')
]

COMPUTATION_FREQUENCY_CHOICES = [
    ('once_daily', '12:40'),
    ('once_monthly', '14:00 on the 1st day of the month')
]

BANK_ID_CHOICES =[
    ('0000001', 'KCB Bank Kenya Limited'),
    ('0000002', 'Standard Chartered Bank Kenya Limited'),
    ('0000003', 'ABSA Bank Kenya PLC'),
    ('0000005', 'Bank of India'),
    ('0000006', 'Bank of Baroda (Kenya) Ltd'),
    ('0000007', 'NCBA Kenya PLC'),
    ('0000010', 'Prime Bank Ltd'),
    ('0000011', 'Co-operative Bank of Kenya Limited'),
    ('0000012', 'National Bank of Kenya Ltd'),
    ('0000014', 'M-Oriental Bank Limited'),
    ('0000016', 'Citibank N.A. Kenya'),
    ('0000017', 'Habib Bank AG Zurich'),
    ('0000018', 'Middle East Bank Kenya Limited'),
    ('0000019', 'Bank of Africa Kenya Limited'),
    ('0000023', 'Consolidated Bank of Kenya Ltd'),
    ('0000025', 'Credit Bank Limited'),
    ('0000026', 'Access Bank (Kenya) Limited'),
    ('0000030', 'Chase Bank (K) Limited'),
    ('0000031', 'Stanbic Bank Kenya Limited'),
    ('0000035', 'African Banking Corporation Limited'),
    ('0000039', 'Imperial Bank Ltd'),
    ('0000043', 'Ecobank Kenya Limited'),
    ('0000049', 'Spire Bank Ltd'),
    ('0000050', 'Paramount Bank Limited'),
    ('0000051', 'Kingdom Bank Limited'),
    ('0000053', 'Guaranty Trust Bank (Kenya) Limited'),
    ('0000054', 'Victoria Commercial Bank Limited'),
    ('0000055', 'Guardian Bank Limited'),
    ('0000057', 'I&M Bank Ltd'),
    ('0000059', 'Development Bank of Kenya Ltd'),
    ('0000060', 'SBM Bank (Kenya) Limited'),
    ('0000063', 'Diamond Trust Bank (K) Limited'),
    ('0000064', 'Charterhouse Bank Ltd'),
    ('0000065', 'Mayfair CIB Bank Limited'),
    ('0000066', 'Sidian Bank Limited'),
    ('0000068', 'Equity Bank Kenya Limited'),
    ('0000070', 'Family Bank Limited'),
    ('0000072', 'Gulf African Bank Limited'),
    ('0000074', 'First Community Bank Ltd'),
    ('0000075', 'DIB Bank Kenya Limited'),
    ('0000076', 'UBA Kenya Bank Limited'),
    ('0000083', 'HFC Limited'),
    ('0500001', 'Faulu Microfinance Bank Limited'),
    ('0500002', 'Kenya Women Microfinance Bank PLC'),
    ('0500003', 'SMEP Microfinance Bank Limited'),
    ('0500004', 'Key Microfinance Bank Limited'),
    ('0500005', 'Rafiki Microfinance Bank Limited'),
    ('0500006', 'Century Microfinance Bank Limited'),
    ('0500007', 'Sumac Microfinance Bank Limited'),
    ('0500008', 'U & I Microfinance Bank Limited'),
    ('0500011', 'Daraja Microfinance Bank Limited'),
    ('0500012', 'Caritas Microfinance Bank Limited'),
    ('0500013', 'Maisha Microfinance Bank Limited'),
    ('0500014', 'UWEZO Microfinance Bank Limited'),
    ('0500202', 'Choice Microfinance Bank Limited'),
    ('0500016', 'Muungano Microfinance Bank Limited'),
    ('0300003', 'Alpha Forex Bureau Ltd'),
    ('0300009', 'Aristocrats Forex Bureau Ltd'),
    ('0300010', 'Bamburi Forex Bureau Ltd'),
    ('0300011', 'Bay Forex Bureau (Nairobi) Ltd'),
    ('0300014', 'Muthaiga-ABC Forex Bureau Ltd'),
    ('0300020', 'Central Forex Bureau Ltd'),
    ('0300023', 'Classic Forex Bureau Limited'),
    ('0300025', 'Commercial Forex Bureau Limited'),
    ('0300026', 'Conference Forex Bureau Company Limited'),
    ('0300028', 'Continental Forex Bureau Ltd'),
    ('0300029', 'Cosmos Forex Bureau Ltd'),
    ('0300042', 'Forex Bureau Afro Ltd'),
    ('0300045', 'Gateway Forex Bureau Ltd'),
    ('0300046', 'Giant Forex Bureau de Change Ltd'),
    ('0300048', 'Give and Take Forex Bureau Ltd'),
    ('0300050', 'Glory Forex Bureau Ltd'),
    ('0300051', 'GNK Forex Bureau Ltd'),
    ('0300056', 'Industrial Area Forex Bureau Ltd'),
    ('0300057', 'Island Forex Bureau Ltd'),
    ('0300059', 'Junction Forex Bureau Limited'),
    ('0300062', 'Kenza Exchange Bureau Ltd'),
    ('0300063', 'La’che Forex Bureau Ltd'),
    ('0300066', 'Leo Forex Bureau Ltd'),
    ('0300067', 'Link Forex Bureau Ltd'),
    ('0300070', 'Maritime Forex Bureau Ltd'),
    ('0300074', 'Middletown Forex Bureau Ltd'),
    ('0300076', 'Mona Bureau De Change Ltd'),
    ('0300077', 'Moneypoint Forex Bureau Ltd'),
    ('0300078', 'Morgan Forex Bureau De Change Ltd'),
    ('0300079', 'Mustaqbal Forex Bureau Ltd'),
    ('0300081', 'Nairobi Bureau De Change Ltd'),
    ('0300083', 'Namanga Forex Bureau Ltd'),
    ('0300085', 'Nawal Forex Bureau Ltd'),
    ('0300087', 'Offshore Forex Bureau Limited'),
    ('0300089', 'Pacific Forex Bureau Limited'),
    ('0300090', 'Peaktop Bureau De Change Ltd'),
    ('0300091', 'Pearl Forex Bureau Ltd'),
    ('0300092', 'Pel Forex Bureau Ltd'),
    ('0300096', 'Pwani Forex Bureau Ltd'),
    ('0300097', 'Avenue Forex Bureau Limited'),
    ('0300099', 'Regional Forex Bureau Limited'),
    ('0300100', 'Rift Valley Forex Bureau Ltd'),
    ('0300102', 'Satellite Forex Bureau Ltd'),
    ('0300104', 'Simba Forex Bureau Limited'),
    ('0300105', 'Sky Forex Bureau Limited'),
    ('0300106', 'Solid Exchange Bureau Ltd'),
    ('0300108', 'Sterling Forex Bureau Ltd'),
    ('0300109', 'Sunny Forex Bureau Limited'),
    ('0300111', 'Taipan Forex Bureau Ltd'),
    ('0300113', 'Trade Bureau De Change Ltd'),
    ('0300114', 'Travel Point Forex Bureau Limited'),
    ('0300115', 'Travellers Forex Bureau Ltd'),
    ('0300117', 'Union Forex Bureau Ltd'),
    ('0300118', 'Victoria Forex Bureau De Change Ltd'),
    ('0300120', 'Wallstreet Bureau De Change Ltd'),
    ('0300122', 'Westlands Forex Bureau Ltd'),
    ('0300123', 'Yaya Centre Exchange Bureau Ltd'),
    ('0300128', 'Green Exchange Forex Bureau Limited'),
    ('0300129', 'CBD Forex Bureau Limited'),
    ('0300131', 'Magnum Forex Bureau De Change Ltd'),
    ('0300135', 'Gala Forex Bureau Ltd'),
    ('0300142', 'Sisi Forex Bureau Limited'),
    ('0300143', 'Rand Forex Bureau Limited'),
    ('0300146', 'Boston Forex Bureau Limited'),
    ('0300148', 'Southend Forex Bureau Ltd'),
    ('0300149', 'Springs Forex Bureau Limited'),
    ('0600001', 'Credit Reference Bureau Africa Limited'),
    ('0600002', 'Metropol Credit Reference Bureau Limited'),
    ('0600003', 'Creditinfo Credit Reference Bureau Kenya Limited'),
    ('0700001', 'Dahabshiil Money Transfer Company Limited'),
    ('0700005', 'Amal Express Money Transfer Limited'),
    ('0700006', 'Iftin Express Money Transfer Limited'),
    ('0700007', 'Juba Express Money Transfer Limited'),
    ('0700009', 'Kaah Express Money Transfer Limited'),
    ('0700010', 'Amana Money Transfer Ltd'),
    ('0700011', 'Bakaal Express Money Transfer Ltd'),
    ('0700012', 'Safaricom Money Transfer Services Limited'),
    ('0700013', 'Hodan Global Money Remittance and Exchange Limited'),
    ('0700014', 'Tawakal Money Transfer Limited'),
    ('0700016', 'Flex Money Transfer Limited'),
    ('0700017', 'Taaj Money Transfer Limited'),
    ('0700018', 'Upesi Money Transfer Limited'),
    ('0700019', 'Real Value Money Transfer Limited'),
    ('0700020', 'PostBank Money Transfer Services Limited'),
    ('0700021', 'Postal Corporation of Kenya Money Transfer Services'),
    ('0700023', 'Airtel Money Transfer Limited'),
    ('0700024', 'Mobex Money Transfer Services Ltd'),
    ('0700026', 'Mukuru Money Transfer Limited'),
    ('0000066 NOHC', 'Bakki Holdco Limited (Centum Group)'),
    ('0000068 NOHC', 'Equity Group Holdings Limited'),
    ('0000083 NOHC', 'HF Group Limited'),
    ('0000057 NOHC', 'I&M Holdings Limited'),
    ('0000001 NOHC', 'KCB Group PLC'),
    ('0000014 NOHC', 'M Holdings Limited'),
    ('0000007 NOHC', 'NCBA Group PLC'),
    ('0000031 NOHC', 'Stanbic Holdings PLC'),
    ('1000001', 'Bank of China Limited - Kenya Representative Office'),
    ('1000002', 'Bank of Kigali Ltd - Kenya Representative Office'),
    ('1000003', 'FirstRand Bank limited - Kenya Representative Office'),
    ('1000004', 'HDFC Bank Limited - Kenya Representative Office'),
    ('1000005', 'Mauritius Commercial Bank Limited - Kenya Representative Office'),
    ('1000006', 'Nedbank Limited - Kenya Representative Office'),
    ('1000007', 'Co-operative Rabobank U.A - Kenya Representative Office'),
    ('1000008', 'Societe Generale - Kenya Representative Office'),
    ('1000009', 'BAHL - Kenya Representative Office'),
    ('100-CBK', 'Central Bank of Kenya'),
    ('101-SACCO', 'Sacco'),
    ('102-FIN', 'Fintechs'),
    ('103-OTH', 'Anyother')
]

CHANNEL_SETTLEMENT_CHOICES = [
    ('CPG01', 'MPESA'),
    ('CPG02', 'AIRTEL MONEY'),
    ('CPG03', 'TKASH'),
    ('CPG04', 'PESALINK'),
    ('CPG09', 'JAMBOPAY'),
    ('CPG10', 'CELLULANT'),
    ('CPG11', 'FINSERVE'),
    ('CPG05', 'INTERSWITCH'),
    ('CPG06', 'KENSWITCH'),
    ('CPG07', 'RTGS'),
    ('CPG08', 'EFT'),
    ('CPG99', 'Any Other')
]

REJECTIONS_CHOICES = [
    ('TRRC01', 'System Downtime'),
    ('TRRC02', 'Wrong credentials'),
    ('TRRC03', 'Insufficient Balance'),
    ('TRRC04', 'Network issues'),
    ('TRRC05','No RejectionType'),
    ('TRRC99', 'Others (specify)')
]

BILL_CLASSIFICATION_CODE = [
    ('ABC01', 'Safaricom'),
    ('ABC02', 'Airtel'),
    ('ABC03', 'Telkom'),
    ('ABC04', 'JTL'),
    ('ABC99', 'Any other (Specify)'),
    ('UBC01', 'KPLC - prepaid'),
    ('UBC02', 'KPLC - postpaid'),
    ('UBC03', 'Nairobi water'),
    ('UBC04', 'NHIF'),
    ('UBC05', 'Safaricom'),
    ('UBC99', 'Any other (Specify)'),
    ('TBC01', 'ZUKU'),
    ('TBC02', 'GOTV'),
    ('TBC03', 'DSTV'),
    ('TBC04', 'Startimes'),
    ('TBC05', 'Multichoice'),
    ('TBC99', 'Any other (Specify)'),
    ('EBC99', 'Events'),
    ('OBC99', 'Any Other')
]

DENOMINATION_CODE_CHOICES = [
    ('KESB1000', '1000 - 1,000/- New Generation Note'),
    ('KESB500', '500 - 500/- New Generation Note'),
    ('KESB200', '200 - 200/- New Generation Note'),
    ('KESB100', '100 - 100/- New Generation Note'),
    ('KESB50', '50 - 50/- New Generation Note'),
    ('KES1000', '1000 - 1000/- Old Generation Note'),
    ('KES500', '500 - 500/- Old Generation Note'),
    ('KES200', '200 - 200/- Old Generation Note'),
    ('KES100', '100 - 100/- Old Generation Note'),
    ('KES50', '50 - 50/- Old Generation Note'),
    ('KES20', '20 - 20/- Old Generation Note'),
    ('KES10', '10 - 10/- Old Generation Note'),
    ('KES5', '5 - 5/- Old Generation Note'),
    ('KES40', '40 - 40/- Old or New Generation Coin'),
    ('KES.20', '20 - 20/- Old or New Generation Coin'),
    ('KES.10', '10 - 10/- Old or New Generation Coin'),
    ('KES.5', '5 - 5/- Old or New Generation Coin'),
    ('KES1', '1 - 1/- Old or New Generation Coin'),
    ('KES.050', '0.5'),
]

SEGMENTATION_CODE_CHOICES = [
    ('SG01', 'P2P - Person to Person'),
    ('SG02', 'P2B - Person to Business'),
    ('SG03', 'P2G - Person to Government'),
    ('SG04', 'B2P - Business to Person'),
    ('SG05', 'B2B - Business to Business'),
    ('SG06', 'B2G - Business to Government'),
    ('SG07', 'G2P - Government to Person'),
    ('SG08', 'G2B - Government to Business'),
    ('SG09', 'G2G - Government to Government'),
]

BUSINESS_SIZE_CODE_CHOICES = [
    ('BSC01', 'Micro enterprises - <= 500,000'),
    ('BSC02', 'Small enterprises - > 500,000 and < 5,000,000'),
    ('BSC03', 'Medium enterprises - > 5,000,001 and < 100,000,000'),
    ('BSC04', 'Large enterprises - > 100,000,001'),
    ('BSC05', 'Individuals - Individuals that are not in business. E.g. salaried customers'),
    ('BSC06', 'Non profit organizations - NGOs/Churches/Charity/Welfare organisations'),
]

# not sure if the below has choices

TYPE_OF_DIRECTOR_CHOICES = [
    ('TD01', 'Individual'),
    ('TD02', 'Company'),
    ('TD03', 'Trust'),
    ('TD04', 'Partnership'),
    ('TD05', 'Other'),
]
DESIGNATION_CHOICES = [
    ('D01', 'Chairman'),
    ('D02', 'Director'),
    ('D03', 'Secretary'),
    ('D04', 'Treasurer'),
    ('D05', 'Other'),
]
SHAREHOLDER_TYPE_CHOICES = [
    ('ST01', 'Individual'),
    ('ST02', 'Company'),
    ('ST03', 'Trust'),
    ('ST04', 'Partnership'),
    ('ST05', 'Other'),
]
COMPLAINT_FREQUENCY_CHOICES = [
    ('CF01', 'Daily'),
    ('CF02', 'Weekly'),
    ('CF03', 'Monthly'),
    ('CF04', 'Quarterly'),
    ('CF05', 'Yearly'),
    ('CF06', 'Never'),
]


TRUST_ACCOUNT_DETAILS_CHOICES = [
    ('TFP01', 'Cash holdings (Fixed Deposit)'),
    ('TFP02', 'Cash holdings (Current)'),
    ('TFP03', 'Cash holdings (Fixed Deposit) in foreign currency account'),
    ('TFP04', 'Cash holdings (Current) in foreign currency account'),
    ('TFP05', 'Treasury bills'),
    ('TFP06', 'Treasury bonds'),
    ('TFP99', 'Any other'),

]

TRUST_ACCOUNT_UTILIZED_DETAILS_CHOICES = [
    ('DBT01',	'Banks charges'),
    ('DBT02',	'Management fees'),
    ('DBT03',	'Stamp duty'),
    ('DBT04',	'Donations'),
    ('DBT05',	'Custody fees'),
    ('DBT06',	'Audit fees'),
    ('DBT07',	'Withholding taxes'),
    ('DBT08',	'Field not applicable'),
    ('DBT99',	'Any others debit type'),

]

FRAUD_CATEGORY_FLAG_CHOICES = [
    ('FCT01', 'Actual'),
    ('FCT02', 'Attempted'),
]

SUB_FRAUD_FRAUD_CHOICES = [
    ('IC01',	'Wallet to wallet registered to registered'),
    ('IC02',	'Wallet to wallet registered to unregistered'),
    ('IC03',	'wallet to wallet unregistered to registered') ,
    ('IC04',	'Cross-network wallet to mobile number ( Interop)'),
    ('IC05',	'Local mobile wallet to international mobile money wallet'),
    ('IC06',	'Bulk payment from business mobile money wallet to personal mobile money wallet'),
    ('IC07',	'Bank account to mobile money wallet'),
    ('IC08',	'Mobile money wallet to bank account'),
    ('IC09',	'Agent cash and float'),
    ('IC10',	'Deposit at branch or super agent'),
    ('IC11',	'Withdrawal at branch or super agent'),
    ('IC12',	'Float transfer to other agent'),
    ('IC13',	'Mobile money wallet to merchant or business paybill'),
    ('IC14',	'Mobile money wallet to till'),
    ('IC99',	'Any other instrument type'),
    ('SG01',	'P2P - Person to Person'),
    ('SG02',	'P2B - Person to Business'),
    ('SG03',	'P2G - Person to Government'),
    ('SG04',	'B2P - Business to Person'),
    ('SG05',	'B2B - Business to Business'),
    ('SG06',	'B2G - Business to Government'),
    ('SG07',	'G2P - Government to Person'),
    ('SG08',	'G2G - Government to Business'),
    ('SG09',	'G2B - Government to Government'),
    # ('I', 'Individual'),
    # ('B', 'Business'),
    # ('G', 'Government/ Public entity'),
    ('SS',	'Sim swap'),
    ('CONSEND',	'Individuals conned into sending money') ,
    ('CONPIN',	'PIN theft'),
    ('CONIDEN',	'Identity theft'),
    ('CONIMPER',	'Impersonification'),
    # ('I',	'Individual'),
    # ('B',	'Business'),
    # ('G',	'Government/ Public entity'),
    # ('I',	'Individual'),
    # ('B',	'Business'),
    # ('G',	'Government/ Public entity'),
    ('ATM',	'ATM'),
    ('AG',	'Agent'),

]