# Generated by Django 5.0.4 on 2024-08-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilepspcustomerinfo',
            name='psp_id',
            field=models.CharField(choices=[('0800001', 'Safaricom Plc'), ('0800002', 'Airtel Money Kenya Limited'), ('0800003', 'Telkom Kenya Limited'), ('0800004', 'Mobile Pay Limited'), ('0800005', 'Kenswitch Limited'), ('0800006', 'Interswitch East Africa (K) Limited'), ('0800007', 'Integrated Payment Services Limited'), ('0800008', 'Viewtech Limited'), ('0800009', 'Web Tribe Limited'), ('0800010', 'Finserve Africa Limited'), ('0800011', 'Cellulant Kenya Limited'), ('0800012', 'Pesapal Limited'), ('0800013', 'Fivespot Limited'), ('0800014', 'Craft Silicon Limited'), ('0800015', 'Virtual Pay International Limited'), ('0800016', 'Direct Pay Limited'), ('0800017', 'Pesawise Services Limited'), ('0800018', 'Paystack Payments Kenya Limited'), ('0800019', 'Wakandi Kenya Limited'), ('0800020', 'Kenya Airports Parking Services (KAPS) Limited'), ('0800021', 'Loop Payco Limited'), ('0800022', 'DLocal Payments Kenya Limited'), ('0800023', 'Pesaflow Limited'), ('0800024', 'Kenya Commerce Exchange Service Bureau Limited'), ('0800025', 'PayU Kenya Limited'), ('0800026', 'Dolcepay Kenya Limited'), ('0800027', 'Unlimint Kenya Limited'), ('0800028', 'Gladys Technologies Limited'), ('0800029', 'Mamlaka Hub and Spoke Limited'), ('0800030', 'Eclectics International Limited'), ('0800031', 'Jumia Payment Services Kenya Limited'), ('0800032', 'Amsuka Capital Limited'), ('0800033', 'Sky World Limited'), ('0800034', 'Kashia Services Limited'), ('0800035', 'Data Integrated Limited'), ('0800036', 'Tanda Agent Limited')], default='0800009', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilepspcustomerinfo',
            name='row_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
