# Generated by Django 5.0.4 on 2024-11-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_card_switch_info_counterfeit_transactions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='psp_customer_compaints',
        ),
    ]
