# Generated by Django 5.0.4 on 2024-08-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_mobilepspcustomerinfo_psp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilepspcustomerinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='mobilepspcustomerinfo',
            name='row_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
