# Generated by Django 5.0.4 on 2024-08-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_mobilepspcustomerinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepspcustomerinfo',
            name='row_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
