# Generated by Django 5.0.4 on 2024-08-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_mobilepspcustomerinfo_row_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePspTransactionCategorization',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('psp_id', models.CharField(choices=[('0800001', 'Safaricom Plc'), ('0800002', 'Airtel Money Kenya Limited'), ('0800003', 'Telkom Kenya Limited'), ('0800004', 'Mobile Pay Limited'), ('0800005', 'Kenswitch Limited'), ('0800006', 'Interswitch East Africa (K) Limited'), ('0800007', 'Integrated Payment Services Limited'), ('0800008', 'Viewtech Limited'), ('0800009', 'Web Tribe Limited'), ('0800010', 'Finserve Africa Limited'), ('0800011', 'Cellulant Kenya Limited'), ('0800012', 'Pesapal Limited'), ('0800013', 'Fivespot Limited'), ('0800014', 'Craft Silicon Limited'), ('0800015', 'Virtual Pay International Limited'), ('0800016', 'Direct Pay Limited'), ('0800017', 'Pesawise Services Limited'), ('0800018', 'Paystack Payments Kenya Limited'), ('0800019', 'Wakandi Kenya Limited'), ('0800020', 'Kenya Airports Parking Services (KAPS) Limited'), ('0800021', 'Loop Payco Limited'), ('0800022', 'DLocal Payments Kenya Limited'), ('0800023', 'Pesaflow Limited'), ('0800024', 'Kenya Commerce Exchange Service Bureau Limited'), ('0800025', 'PayU Kenya Limited'), ('0800026', 'Dolcepay Kenya Limited'), ('0800027', 'Unlimint Kenya Limited'), ('0800028', 'Gladys Technologies Limited'), ('0800029', 'Mamlaka Hub and Spoke Limited'), ('0800030', 'Eclectics International Limited'), ('0800031', 'Jumia Payment Services Kenya Limited'), ('0800032', 'Amsuka Capital Limited'), ('0800033', 'Sky World Limited'), ('0800034', 'Kashia Services Limited'), ('0800035', 'Data Integrated Limited'), ('0800036', 'Tanda Agent Limited')], max_length=25)),
                ('reporting_date', models.DateField()),
                ('sub_transaction_code', models.CharField(choices=[('P2P', 'Person to Person payments'), ('B2E', 'Bank to E-wallet'), ('E2B', 'E-Wallet to Bank'), ('ATMD', 'ATM cash deposits at banks'), ('ATMW', 'ATM cash withdrawals from banks'), ('ARTP', 'Airtime purchase'), ('DTP', 'Data purchases'), ('P2B01', 'Person to Business payments'), ('P2B02', 'Person to Business payments'), ('P2B03', 'Person to Business payments'), ('P2B04', 'Person to Business payments'), ('P2B05', 'Person to Business payments'), ('P2B06', 'Person to Business payments'), ('P2B07', 'Person to Business payments'), ('P2B08', 'Person to Business payments'), ('P2B09', 'Person to Business payments'), ('P2B10', 'Person to Business payments'), ('P2B11', 'Person to Business payments'), ('P2B12', 'Person to Business payments'), ('P2B13', 'Person to Business payments'), ('P2B14', 'Person to Business payments'), ('P2B15', 'Person to Business payments'), ('P2B16', 'Person to Business payments'), ('P2B17', 'Person to Business payments'), ('P2B18', 'Person to Business payments'), ('P2B19', 'Person to Business payments'), ('P2B20', 'Person to Business payments'), ('P2B21', 'Person to Business payments'), ('P2B22', 'Person to Business payments'), ('P2B23', 'Person to Business payments'), ('P2B24', 'Person to Business payments'), ('P2G01', 'Person to Government payments'), ('P2G02', 'Person to Government payments'), ('P2G99', 'Person to Government payments'), ('G2P01', 'Government to Person payments'), ('G2P02', 'Government to Person payments'), ('G2P99', 'Government to Person payments'), ('G2B01', 'Government to Business payments'), ('G2B02', 'Government to Business payments'), ('G2B99', 'Government to Business payments'), ('BG2P01', 'Business or Government to Person payments'), ('BG2P02', 'Business or Government to Person payments'), ('BG2P99', 'Business or Government to Person payments'), ('OTCD', 'Other Transaction Code')], max_length=10)),
                ('band_code', models.CharField(choices=[('BNC01', '1 - 49'), ('BNC02', '50 - 100'), ('BNC03', '101 - 500'), ('BNC04', '501 - 1000'), ('BNC05', '1001 - 1500'), ('BNC06', '1501 - 2500'), ('BNC07', '2501 - 3500'), ('BNC08', '3501 - 5000'), ('BNC9', '5001 - 7500'), ('BNC10', '7501 - 10000'), ('BNC11', '10001 - 15000'), ('BNC12', '15001 - 20000'), ('BNC13', '20001 - 25000'), ('BNC14', '25001 - 30000'), ('BNC15', '30001 - 35000'), ('BNC16', '35001 - 40000'), ('BNC17', '40001 - 45000'), ('BNC18', '45001 - 50000'), ('BNC19', '50001 - 70000'), ('BNC20', '70001 - 150000'), ('BNC21', '150001-250000'), ('BNC22', 'Any other band')], max_length=25)),
                ('volume_of_transactions', models.PositiveIntegerField()),
                ('value_of_transactions', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
