# Generated by Django 5.1.1 on 2024-11-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_incidents_data_psp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psp_customer_info',
            old_name='sub_county_code',
            new_name='sub_country_code',
        ),
    ]
