# Generated by Django 5.0.4 on 2024-09-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_mobilepspagentsinformation_mobilepspinteroperability_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobilePspCustomerInfo',
            new_name='Psp_Customer',
        ),
        migrations.RenameModel(
            old_name='MobilePspTransactionCategorization',
            new_name='Psp_Transac_Categorization',
        ),
    ]
