# Generated by Django 5.0.4 on 2024-10-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_interoperability_data_psp_agents_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psp_customer_info',
            name='age_code',
            field=models.CharField(choices=[('4', '0-4'), ('9', '5-9'), ('14', '10-14'), ('19', '15-19'), ('24', '20-24'), ('29', '25-29'), ('34', '30-34'), ('39', '35-39'), ('44', '40-44'), ('49', '45-49'), ('54', '50-54'), ('59', '55-59'), ('64', '60-64'), ('69', '65-69'), ('74', '70-74'), ('79', '75-79'), ('80', '80+')], max_length=10),
        ),
    ]
