# Generated by Django 5.0.4 on 2024-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_card_switch_info_counterfeit_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_activity_info',
            name='hour_of_day',
            field=models.CharField(choices=[('HH01', '00:00 - 00:59'), ('HH02', '01:00 - 01:59'), ('HH03', '02:00 - 02:59'), ('HH04', '03:00 - 03:59'), ('HH05', '04:00 - 04:59'), ('HH06', '05:00 - 05:59'), ('HH07', '06:00 - 06:59'), ('HH08', '07:00 - 07:59'), ('HH09', '08:00 - 08:59'), ('HH10', '09:00 - 09:59'), ('HH11', '10:00 - 10:59'), ('HH12', '11:00 - 11:59'), ('HH13', '12:00 - 12:59'), ('HH14', '13:00 - 13:59'), ('HH15', '14:00 - 14:59'), ('HH16', '15:00 - 15:59'), ('HH17', '16:00 - 16:59'), ('HH18', '17:00 - 17:59'), ('HH19', '18:00 - 18:59'), ('HH20', '19:00 - 19:59'), ('HH21', '20:00 - 20:59'), ('HH22', '21:00 - 21:59'), ('HH23', '22:00 - 22:59'), ('HH24', '23:00 - 23:59')], max_length=6),
        ),
    ]
